# Eigenständig formulierte, IHK-nahe Übungsaufgaben für MIKP.
# Die Themen orientieren sich an wiederkehrenden Prüfungsmustern, nicht an einer wortgleichen Übernahme von Prüfungsaufgaben.

MIKP_AUFGABEN = []

def mc(i,thema,frage,antworten,richtig,tipp,erk):
    MIKP_AUFGABEN.append({"id":f"MIKP{i:03d}","thema":thema,"schwierigkeit":"Leicht" if i%3==0 else "Mittel","typ":"multiple_choice","aufgabe":frage,"antworten":antworten,"richtige_antwort":richtig,"tipp":tipp,"erklaerung":erk})

def offen(i,thema,frage,loesung,tipp="",visualisierung=None):
    d={"id":f"MIKP{i:03d}","thema":thema,"schwierigkeit":"Mittel" if i%4 else "Schwer","typ":"offen","aufgabe":frage,"musterloesung":loesung,"tipp":tipp}
    if visualisierung: d["visualisierung"]=visualisierung
    MIKP_AUFGABEN.append(d)

def rechnen(i,thema,frage,gegeben,gesucht,ergebnis,einheit,formel,weg,visualisierung=None):
    d={"id":f"MIKP{i:03d}","thema":thema,"schwierigkeit":"Mittel","typ":"rechnen","aufgabe":frage,"gegeben":gegeben,"gesucht":gesucht,"ergebnis":ergebnis,"einheit":einheit,"formel":formel,"loesungsweg":weg}
    if visualisierung: d["visualisierung"]=visualisierung
    MIKP_AUFGABEN.append(d)

# Daten / IT
mc(1,"Informations- und Datenmanagement","Welche Aussage beschreibt Stammdaten am besten?",["Sie entstehen nur bei jeder einzelnen Buchung.","Sie sind relativ konstante Grunddaten eines Objekts.","Sie dürfen nie verändert werden.","Sie sind ausschließlich personenbezogene Daten."],"Sie sind relativ konstante Grunddaten eines Objekts.","Denke an Artikelnummer oder Lieferantenadresse.","Stammdaten beschreiben relativ dauerhafte Merkmale. Bewegungsdaten entstehen dagegen durch laufende Vorgänge.")
offen(2,"Informations- und Datenmanagement","Beschreibe die drei Schutzziele Verfügbarkeit, Integrität und Vertraulichkeit im Zusammenhang mit betrieblichen Daten.",["Verfügbarkeit: Daten und Systeme sind bei Bedarf nutzbar.","Integrität: Daten bleiben korrekt, vollständig und vor unbemerkter Veränderung geschützt.","Vertraulichkeit: Nur berechtigte Personen können Daten einsehen bzw. nutzen."])
offen(3,"Informations- und Datenmanagement","Nenne vier technische oder organisatorische Maßnahmen, mit denen ein Unternehmen die Verfügbarkeit seiner Daten erhöhen kann.",["Regelmäßige Backups mit Wiederherstellungstest.","Redundante Server, Datenträger oder Systeme.","USV bzw. Notstromversorgung.","Updates und vorbeugende Systemwartung.","Notfall- und Wiederanlaufkonzept.","Geeigneter Schutz vor Schadsoftware und Angriffen."])
mc(4,"Informations- und Datenmanagement","Was ist ein Bewegungsdatum?",["Artikelbezeichnung","Personalnummer","Wareneingang von 50 Stück am heutigen Tag","Anschrift eines Lieferanten"],"Wareneingang von 50 Stück am heutigen Tag","Gesucht ist ein Datum, das durch einen Vorgang entsteht.","Ein Wareneingang ist ein laufender betrieblicher Vorgang und erzeugt Bewegungsdaten.")
offen(5,"Informations- und Datenmanagement","Ein Betrieb erfasst Arbeitszeiten digital. Nenne drei organisatorische und drei technische Maßnahmen zum Schutz der personenbezogenen Daten.",["Organisatorisch: Rollen/Berechtigungen festlegen, Beschäftigte schulen, Lösch- und Aufbewahrungsregeln definieren.","Technisch: starke Authentifizierung/MFA, Verschlüsselung, Protokollierung bzw. Zugriffsschutz."])
offen(6,"Informations- und Datenmanagement","Beschreibe vier typische Aufgaben einer IT-Administration, die zur Datensicherheit beitragen.",["Benutzer und Zugriffsrechte verwalten.","Updates/Patches einspielen.","Datensicherungen durchführen und Wiederherstellung prüfen.","Firewall, Virenschutz und Sicherheitsprotokolle überwachen.","Systeme und Ausfälle überwachen."])
mc(7,"Informations- und Datenmanagement","Welche Auswertung ist typisch für ein Datenbanksystem?",["Datensätze nach Kriterien filtern und zusammenfassen","Papierunterlagen laminieren","Maschinen mechanisch ausrichten","Werkzeuge härten"],"Datensätze nach Kriterien filtern und zusammenfassen","Eine Datenbank hilft beim Suchen und Auswerten.","Datenbanksysteme ermöglichen Abfragen, Filter, Sortierungen, Berichte und statistische Auswertungen.")
offen(8,"Informations- und Datenmanagement","Erkläre zwei Vorteile eines ERP-Systems für einen Industriebetrieb.",["Gemeinsame Datenbasis für mehrere Unternehmensbereiche.","Weniger Mehrfacherfassung und dadurch weniger Übertragungsfehler.","Aktuellere Informationen für Planung und Steuerung.","Bessere Verknüpfung von Einkauf, Lager, Produktion, Vertrieb und Controlling."])

# Projektmanagement
mc(9,"Projektmanagement","Welche drei Größen bilden das magische Dreieck des Projektmanagements?",["Zeit, Kosten, Leistung/Qualität","Personal, Material, Maschine","Planen, Führen, Kontrollieren","Einkauf, Produktion, Vertrieb"],"Zeit, Kosten, Leistung/Qualität","Es geht um drei miteinander konkurrierende Projektziele.","Zeit, Kosten und Leistung/Qualität beeinflussen sich gegenseitig.")
offen(10,"Projektmanagement","Eine neue Bearbeitungsmaschine soll beschafft werden. Beschreibe vier sinnvolle Planungsschritte nach der Projektdefinition.",["Strukturplanung: Projekt in Teilaufgaben/Arbeitspakete zerlegen.","Ablaufplanung: Reihenfolge und Abhängigkeiten festlegen.","Terminplanung: Dauern, Termine und Puffer bestimmen.","Ressourcenplanung: Personal, Technik und Material zuordnen.","Informationsplanung: Informationswege und -termine festlegen."])
offen(11,"Projektmanagement","Nenne vier Risikoarten eines Maschinenprojekts und jeweils eine mögliche vorbeugende Maßnahme.",["Terminrisiko – Zeitreserven bzw. Alternativplan einplanen.","Personalrisiko – Vertretung/Qualifizierung vorsehen.","Technisches Risiko – Tests und technische Prüfung durchführen.","Kostenrisiko – Budgetreserve und laufende Kostenkontrolle.","Lieferkettenrisiko – Alternativlieferanten prüfen."])
offen(12,"Projektmanagement","Beschreibe vier Schritte einer systematischen Risikoanalyse.",["Risiken identifizieren.","Eintrittswahrscheinlichkeit bewerten.","Schadensausmaß/Auswirkung bewerten.","Risiken priorisieren.","Gegenmaßnahmen planen und Verantwortliche festlegen.","Risiken regelmäßig überwachen."])
mc(13,"Projektmanagement","Was beschreibt ein Lastenheft?",["Wie der Auftragnehmer die Lösung technisch umsetzt","Was der Auftraggeber fordert","Nur die Kosten des Projekts","Nur den Terminplan"],"Was der Auftraggeber fordert","Merksatz: Lastenheft = WAS und WOFÜR.","Das Lastenheft beschreibt Anforderungen und Ziele aus Sicht des Auftraggebers.")
offen(14,"Projektmanagement","Erläutere einen typischen Zielkonflikt im magischen Dreieck des Projektmanagements.",["Wird ein Termin stark verkürzt, können zusätzliche Ressourcen und damit höhere Kosten erforderlich werden.","Werden Kosten stark reduziert, können Umfang/Qualität leiden oder Termine länger werden.","Zusätzliche Leistungsanforderungen können Zeit und Kosten erhöhen."])
offen(15,"Projektmanagement","Nenne vier Informationen, die du für eine Ressourcenplanung benötigst.",["Benötigte Qualifikationen und Personalbedarf.","Verfügbarkeit von Beschäftigten.","Benötigte Maschinen/Betriebsmittel und deren Verfügbarkeit.","Materialbedarf und Liefertermine.","Kosten der Ressourcen.","Zeitpunkt und Dauer des Ressourceneinsatzes."])

# Netzplan / Ablauf
mc(16,"Netzplantechnik und Ablaufplanung","Was kennzeichnet einen Vorgang auf dem kritischen Pfad?",["Er hat den größten Gesamtpuffer.","Sein Gesamtpuffer beträgt 0.","Er hat immer die kürzeste Dauer.","Er darf keine Vorgänger haben."],"Sein Gesamtpuffer beträgt 0.","Kritisch bedeutet: keine zeitliche Reserve.","Vorgänge mit Gesamtpuffer 0 bilden den kritischen Pfad.")
offen(17,"Netzplantechnik und Ablaufplanung","Erkläre FAZ, FEZ, SAZ, SEZ und Gesamtpuffer eines Netzplans.",["FAZ: frühester Anfangszeitpunkt.","FEZ: frühester Endzeitpunkt.","SAZ: spätester Anfangszeitpunkt ohne Projektverzögerung.","SEZ: spätester Endzeitpunkt ohne Projektverzögerung.","Gesamtpuffer: zeitlicher Spielraum; GP = SAZ − FAZ bzw. SEZ − FEZ."])
offen(18,"Netzplantechnik und Ablaufplanung","Erstelle gedanklich einen Netzplan: A dauert 2 Tage. Danach laufen B mit 3 Tagen und C mit 5 Tagen parallel. D dauert 2 Tage und darf erst beginnen, wenn B und C abgeschlossen sind. Bestimme Projektdauer und kritischen Pfad.",["A endet nach Tag 2.","B endet nach Tag 5, C nach Tag 7.","D kann erst nach C starten und endet nach Tag 9.","Projektdauer: 9 Tage.","Kritischer Pfad: A → C → D.","B besitzt 2 Tage zeitlichen Spielraum."],visualisierung={"typ":"netzplan","nodes":[["A",2,0,2,0,2],["B",3,2,5,4,7],["C",5,2,7,2,7],["D",2,7,9,7,9]],"edges":[["A","B"],["A","C"],["B","D"],["C","D"]],"kritisch":["A","C","D"]})
offen(19,"Netzplantechnik und Ablaufplanung","Beschreibe die Regeln der Vorwärts- und Rückwärtsrechnung im Netzplan.",["Vorwärts: FAZ = größter FEZ der Vorgänger; FEZ = FAZ + Dauer.","Rückwärts: SEZ = kleinster SAZ der Nachfolger; SAZ = SEZ − Dauer.","Beim letzten Vorgang wird der SEZ in der Regel auf den Projektendtermin gesetzt."])
offen(20,"Netzplantechnik und Ablaufplanung","Stelle den Ablauf einer Störungsbearbeitung als Flussdiagramm dar: Störung prüfen → selbst behebbar? → ja: beheben → Produktion starten; nein: Instandhaltung rufen → beheben lassen → Produktion starten.",["Start: Störung prüfen.","Entscheidung: selbst behebbar?","Ja-Zweig: selbst beheben → Produktion starten.","Nein-Zweig: Instandhaltung rufen → beheben lassen → Produktion starten.","Entscheidungen werden als Raute, Tätigkeiten als Rechteck und Flüsse als Pfeile dargestellt."],visualisierung={"typ":"flussdiagramm"})
offen(21,"Netzplantechnik und Ablaufplanung","Nenne vier Anwendungsgebiete und drei Vorteile von Flussdiagrammen.",["Anwendungen: Arbeitsprozesse, Informationsflüsse, Qualitätskontrollen, Arbeitssicherheitsabläufe, Programmabläufe.","Vorteile: schnelle Übersicht, höhere Transparenz, Standardisierung, Soll-Ist-Vergleich, Optimierungspotenziale werden sichtbar."])

# Präsentation
mc(22,"Präsentation und Medieneinsatz","Welche Maßnahme verbessert eine Präsentation am ehesten?",["Möglichst viel Text auf jede Folie schreiben","Schriftgröße möglichst klein wählen","Kernaussagen visualisieren und Folien übersichtlich halten","Jede Folie vollständig vorlesen"],"Kernaussagen visualisieren und Folien übersichtlich halten","Weniger ist bei Folien häufig mehr.","Visualisierungen sollen die Aussage unterstützen, nicht den Vortrag ersetzen.")
offen(23,"Präsentation und Medieneinsatz","Beschreibe fünf Kriterien, nach denen eine betriebliche Präsentation bewertet werden kann.",["Klare Zielsetzung und nachvollziehbare Gliederung.","Fachlich richtige und zielgruppengerechte Inhalte.","Sicheres Auftreten und verständliche Sprache.","Passender und lesbarer Medieneinsatz.","Einhaltung der Zeit.","Blickkontakt und Einbeziehung der Teilnehmer."])
offen(24,"Präsentation und Medieneinsatz","Du bereitest eine Sicherheitsunterweisung für eine sprachlich gemischte Gruppe vor. Nenne fünf Maßnahmen, mit denen du die Präsentation zielgruppengerecht gestaltest.",["Einfache, kurze Sprache verwenden.","Fachbegriffe erklären.","Viele Bilder, Symbole und Praxisbeispiele einsetzen.","Verständnis durch Rückfragen kontrollieren.","Wichtige Inhalte wiederholen und schriftlich/visuell sichern.","Bei Bedarf Übersetzungen oder mehrsprachige Hinweise bereitstellen."])
offen(25,"Präsentation und Medieneinsatz","Nenne fünf typische Fehler bei einer Online-Präsentation und beschreibe jeweils kurz, wie du sie vermeidest.",["Technik ungeprüft → vorher Verbindung, Ton, Kamera und Freigabe testen.","Zu kleine/überladene Folien → reduzieren und große Schrift nutzen.","Monotoner Vortrag → Stimme variieren und Pausen setzen.","Keine Aktivierung → Fragen, Abstimmungen oder kurze Aufgaben einbauen.","Störender Hintergrund → ruhige Umgebung und passende Kameraeinstellung.","Folien nur vorlesen → frei erklären und Beispiele nutzen."])
mc(26,"Präsentation und Medieneinsatz","Welches Diagramm eignet sich besonders für eine Entwicklung über mehrere Jahre?",["Liniendiagramm","Kreisdiagramm","Organigramm","Flussdiagramm"],"Liniendiagramm","Die Reihenfolge der Zeitpunkte ist entscheidend.","Ein Liniendiagramm macht zeitliche Trends besonders gut sichtbar.")

# Kommunikation
mc(27,"Kommunikation und Moderation","Was gehört zum aktiven Zuhören?",["Den Gesprächspartner häufig unterbrechen","Wichtige Aussagen mit eigenen Worten wiedergeben","Während des Gesprächs E-Mails bearbeiten","Nur geschlossene Fragen stellen"],"Wichtige Aussagen mit eigenen Worten wiedergeben","Gesucht ist Paraphrasieren.","Paraphrasieren zeigt Aufmerksamkeit und hilft, Missverständnisse zu vermeiden.")
offen(28,"Kommunikation und Moderation","Nenne vier Merkmale des aktiven Zuhörens.",["Ausreden lassen.","Blickkontakt und zugewandte Körperhaltung.","Aussagen paraphrasieren.","Offene Rückfragen stellen.","Gefühle bzw. Kernaussagen spiegeln.","Zusammenfassen."])
offen(29,"Kommunikation und Moderation","Zwischen zwei Mitarbeitern besteht ein Konflikt. Nenne drei Voraussetzungen und vier Kommunikationsgrundsätze für ein erfolgreiches Konfliktgespräch.",["Voraussetzungen: geeigneter ungestörter Rahmen, ausreichende Zeit, Bereitschaft beider Seiten zur Klärung.","Grundsätze: sachlich bleiben, ausreden lassen, konkrete Beobachtungen statt Vorwürfe, Ich-Botschaften, aktiv zuhören, gemeinsame Lösung suchen und Vereinbarungen festhalten."])
offen(30,"Kommunikation und Moderation","Du moderierst eine Ideenfindung. Beschreibe die wichtigsten Schritte von der Vorbereitung bis zur Nachbereitung.",["Auftrag, Ziel, Teilnehmer und Rahmen klären.","Einladung und Material vorbereiten.","Einstieg: Ziel, Ablauf und Regeln erläutern.","Ideen mit geeigneter Methode sammeln.","Ideen strukturieren und bewerten.","Maßnahmen, Verantwortliche und Termine festlegen.","Ergebnisse protokollieren und nachverfolgen."])
mc(31,"Kommunikation und Moderation","Welche Frage ist eine offene Frage?",["Haben Sie die Maschine geprüft?","Ist die Störung behoben?","Wie beurteilen Sie die Ursache der Störung?","War es Fehler A oder Fehler B?"],"Wie beurteilen Sie die Ursache der Störung?","Offene Fragen beginnen häufig mit W-Fragewörtern.","Offene Fragen regen zu einer ausführlicheren Antwort an.")
offen(32,"Kommunikation und Moderation","Nenne drei Dokumente, die bei einer Moderation eingesetzt werden können, und ordne jedem einen Zweck zu.",["Einladung – informiert über Thema, Ort, Termin und Dauer.","Handout/Impulsunterlage – führt in das Thema ein und liefert Informationen.","Moderationskarten/Notizen – halten Ideen fest.","Protokoll – dokumentiert Ergebnisse und Vereinbarungen.","Ergebnisbericht – informiert die auftraggebende Stelle."])

# Statistik / Diagramme
rechnen(33,"Statistik, Kennzahlen und Diagramme","Die Energiekosten steigen von 500.000 € auf 700.000 €. Berechne die prozentuale Veränderung.",["Alter Wert = 500.000 €","Neuer Wert = 700.000 €"],"Prozentuale Veränderung",40,"%","(neu − alt) / alt × 100","(700.000 − 500.000) / 500.000 × 100 = 40 %",visualisierung={"typ":"balken","titel":"Energiekosten im Vergleich","kategorien":["Laufendes Jahr","Kommendes Jahr"],"werte":[500000,700000],"ylabel":"Kosten in €"})
rechnen(34,"Statistik, Kennzahlen und Diagramme","Von 200 Befragten vergeben 60 Personen die Bewertung 4. Berechne die relative Häufigkeit in Prozent.",["Absolute Häufigkeit = 60","Gesamtzahl = 200"],"Relative Häufigkeit",30,"%","absolute Häufigkeit / Gesamtzahl × 100","60 / 200 × 100 = 30 %")
offen(35,"Statistik, Kennzahlen und Diagramme","Nenne vier Regeln für ein prüfungstaugliches Diagramm.",["Aussagekräftiger Titel.","Achsen eindeutig beschriften.","Einheiten angeben.","Sinnvolle Skalierung verwenden.","Bei mehreren Datenreihen eine Legende verwenden.","Werte korrekt und gut lesbar eintragen."])
offen(36,"Statistik, Kennzahlen und Diagramme","Für vier Jahre liegen Auslastungsquoten von 64 %, 72 %, 74 % und 89 % vor. Welche Diagrammart würdest du wählen und warum? Skizziere gedanklich die Darstellung.",["Ein Linien- oder Säulendiagramm ist geeignet.","Für die Entwicklung über die geordnete Zeitachse ist ein Liniendiagramm besonders anschaulich.","x-Achse: Jahr 1 bis 4; y-Achse: Auslastung in %.","Die Werte werden bei 64, 72, 74 und 89 % eingetragen."],visualisierung={"typ":"linie","titel":"Entwicklung der Auslastungsquote","kategorien":["Jahr 1","Jahr 2","Jahr 3","Jahr 4"],"werte":[64,72,74,89],"ylabel":"Auslastung in %"})
offen(37,"Statistik, Kennzahlen und Diagramme","Erkläre, wann Säulen-/Balken-, Linien-, Kreis- und Streudiagramme sinnvoll eingesetzt werden.",["Säule/Balken: Vergleich einzelner Kategorien.","Linie: zeitliche bzw. geordnete Entwicklung.","Kreis: Anteile eines Ganzen bei wenigen Kategorien.","Streudiagramm: Zusammenhang/Korrelation zwischen zwei zahlenmäßigen Merkmalen."])
offen(38,"Statistik, Kennzahlen und Diagramme","Ein Betrieb hat Kostenanteile: Personal 45 %, Material 30 %, Energie 15 %, Sonstiges 10 %. Stelle eine geeignete Diagrammart dar und begründe sie.",["Ein Kreisdiagramm ist geeignet, weil die vier Werte Anteile eines Ganzen von 100 % darstellen.","Die Segmente müssen proportional zu 45 %, 30 %, 15 % und 10 % dargestellt und beschriftet werden."],visualisierung={"typ":"kreis","titel":"Kostenanteile","kategorien":["Personal","Material","Energie","Sonstiges"],"werte":[45,30,15,10]})
offen(39,"Statistik, Kennzahlen und Diagramme","Was bedeutet eine positive Korrelation? Nenne ein betriebliches Beispiel und erläutere, wie sie in einem Streudiagramm aussehen kann.",["Mit zunehmender Ausprägung des einen Merkmals steigt tendenziell auch das andere Merkmal.","Beispiel: Mit steigender Produktionsmenge kann der Energieverbrauch steigen.","Im Streudiagramm liegen die Punkte tendenziell von links unten nach rechts oben.","Korrelation allein beweist keine Ursache-Wirkungs-Beziehung."],visualisierung={"typ":"streu","titel":"Beispiel einer positiven Korrelation","x":[10,20,30,40,50,60],"y":[12,18,29,33,47,55],"xlabel":"Produktionsmenge","ylabel":"Energieverbrauch"})

# Entscheidung / Kreativität
mc(40,"Entscheidungs- und Kreativitätstechniken","Was ist bei einem Brainstorming während der Ideensammlung besonders wichtig?",["Jede Idee sofort bewerten","Kritik zunächst zurückstellen","Nur die Führungskraft darf Ideen nennen","Nur realistische Ideen zulassen"],"Kritik zunächst zurückstellen","Erst sammeln, später bewerten.","Eine frühe Bewertung hemmt die Ideenproduktion.")
offen(41,"Entscheidungs- und Kreativitätstechniken","Beschreibe den grundsätzlichen Ablauf einer Nutzwertanalyse.",["Entscheidungsalternativen und Kriterien festlegen.","Kriterien gewichten.","Alternativen je Kriterium bewerten.","Bewertung mit Gewichtung multiplizieren.","Teilnutzwerte zum Gesamtnutzwert addieren.","Ergebnis beurteilen und Plausibilität prüfen."])
offen(42,"Entscheidungs- und Kreativitätstechniken","Erkläre den paarweisen Vergleich zur Ermittlung von Kriteriengewichten.",["Jedes Kriterium wird mit jedem anderen Kriterium verglichen.","Das wichtigere Kriterium erhält mehr Punkte; bei Gleichstand können beide gleich bewertet werden.","Die Punkte werden je Kriterium summiert.","Aus den Punktsummen werden prozentuale Gewichtungen abgeleitet."])
offen(43,"Entscheidungs- und Kreativitätstechniken","Beschreibe fünf Schritte einer schriftlichen Ideenfindung in einer Gruppe.",["Problem und Ziel erläutern.","Teilnehmer schreiben Ideen selbstständig auf.","Ideen werden weitergegeben oder gesammelt.","Andere Teilnehmer ergänzen/entwickeln Ideen weiter.","Ergebnisse werden zusammengeführt und strukturiert.","Anschließend werden die Ideen bewertet."])
mc(44,"Entscheidungs- und Kreativitätstechniken","Welche Aussage zur ABC-Analyse ist richtig?",["A-Güter sind immer mengenmäßig am häufigsten.","A-Güter haben typischerweise einen hohen Wertanteil und benötigen besondere Aufmerksamkeit.","C-Güter dürfen nicht gelagert werden.","B-Güter sind grundsätzlich unwichtig."],"A-Güter haben typischerweise einen hohen Wertanteil und benötigen besondere Aufmerksamkeit.","A steht für hohe wirtschaftliche Bedeutung.","Die ABC-Analyse priorisiert nach wirtschaftlicher Bedeutung, häufig anhand des Wertanteils.")
offen(45,"Entscheidungs- und Kreativitätstechniken","Nenne zwei Vorteile und zwei Grenzen einer Nutzwertanalyse.",["Vorteile: qualitative und quantitative Kriterien können gemeinsam berücksichtigt werden; Entscheidung wird strukturierter und nachvollziehbarer.","Grenzen: Gewichtungen und Bewertungen enthalten subjektive Anteile; ein scheinbar exakter Zahlenwert kann Scheingenauigkeit erzeugen."])

# Zeitmanagement
mc(46,"Zeit- und Selbstmanagement","Was geschieht nach dem Eisenhower-Prinzip mit einer wichtigen, aber nicht dringenden Aufgabe?",["Sofort streichen","Terminieren und geplant bearbeiten","Immer delegieren","Ignorieren"],"Terminieren und geplant bearbeiten","Wichtig, aber noch nicht dringend: plane Zeit ein.","Diese Aufgaben sollten bewusst terminiert werden, bevor sie dringend werden.")
offen(47,"Zeit- und Selbstmanagement","Erkläre die fünf Schritte der ALPEN-Methode.",["A – Aufgaben notieren.","L – Länge/Dauer schätzen.","P – Pufferzeiten reservieren.","E – Entscheidungen über Prioritäten und Delegation treffen.","N – Nachkontrolle durchführen."])
offen(48,"Zeit- und Selbstmanagement","Beschreibe zwei Methoden, mit denen du als Meister deine eigene Arbeitsorganisation verbessern kannst.",["Eisenhower-Prinzip: Aufgaben nach Wichtigkeit und Dringlichkeit priorisieren.","ALPEN-Methode: Tagesplanung mit Dauer, Puffer, Prioritäten und Nachkontrolle.","Zeitblöcke/Terminplanung: konzentrierte Bearbeitungszeiten reservieren.","Pareto-Prinzip: besonders wirksame Aufgaben zuerst identifizieren."])

# zusätzliche IHK-nahe Mischaufgaben
for i, (thema, frage, loes) in enumerate([
("Informations- und Datenmanagement","Nenne drei Möglichkeiten zur Authentifizierung bei einer digitalen Zeiterfassung.",["Passwort/PIN","Chipkarte/Transponder","biometrisches Merkmal wie Fingerabdruck","Mehrfaktor-Authentifizierung"]),
("Projektmanagement","Nenne vier Maßnahmen, mit denen alle Projektbeteiligten einen aktuellen Informationsstand erhalten.",["Regelmäßige Projektbesprechungen","Zentrale aktuelle Projektdokumentation","Definierte Berichtswege und Verteiler","Änderungen versionieren und aktiv kommunizieren","Projektmanagementsoftware/Dashboard"]),
("Präsentation und Medieneinsatz","Beschreibe drei Maßnahmen, mit denen du die Aufmerksamkeit während einer Präsentation erhöhst.",["Teilnehmer durch Fragen/Aufgaben aktivieren","abwechslungsreichen Medienmix nutzen","Kernpunkte ankündigen und wiederholen","Praxisbeispiele einsetzen","Pausen sinnvoll planen"]),
("Kommunikation und Moderation","Nenne drei positiv motivierende Gesprächstechniken.",["Offene und interessierte Fragen stellen","aktiv zuhören und paraphrasieren","konstruktive Rückmeldung geben","Nutzen und Ziele verdeutlichen","Einwände wertschätzend aufnehmen"]),
("Statistik, Kennzahlen und Diagramme","Nenne vier Diagrammarten, mit denen sich Anteile oder Kategorien darstellen lassen.",["Säulendiagramm","Balkendiagramm","Kreis-/Ringdiagramm","Streifendiagramm"]),
("Netzplantechnik und Ablaufplanung","Nenne drei Vorteile eines Netzplans für die Projektsteuerung.",["Abhängigkeiten werden sichtbar","kritische Vorgänge werden erkannt","Pufferzeiten werden ermittelt","Terminauswirkungen von Verzögerungen können beurteilt werden"]),
("Projektmanagement","Beschreibe zwei Aufgaben der Projektleitung während der Realisierung.",["Soll-Ist-Vergleich von Terminen, Kosten und Leistung durchführen","Abweichungen analysieren und Gegenmaßnahmen einleiten","Information und Koordination der Beteiligten sicherstellen","Änderungen dokumentieren"]),
("Informations- und Datenmanagement","Beschreibe drei Methoden zur Vermeidung von Fehlern bei der Datenerfassung.",["Plausibilitätsprüfungen","Pflichtfelder und Wertebereiche","Auswahllisten statt Freitext","Vier-Augen-Prinzip","automatische Übernahme/Schnittstellen statt Mehrfacheingabe"]),
], start=49):
    offen(i,thema,frage,loes)

def mikp_aufgaben_nach_thema(thema):
    return [a for a in MIKP_AUFGABEN if a["thema"] == thema]
